name: app_name
description: app description
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  logging: ^1.0.2
  rxdart: ^0.27.4


dev_dependencies:
  bloc_test: ^8.5.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
